"use client";

import { useEffect, useState } from "react";
import type { StudyPack } from "@/lib/schema";
import { track } from "@/lib/analytics";
import PackView from "@/components/pack/PackView";

type Language = "en" | "de";

type DemoEntry = {
  slug: string;
  de: { title: string; subtitle: string; examLabel: string };
  en: { title: string; subtitle: string; examLabel: string };
};

const DEMOS: DemoEntry[] = [
  {
    slug: "strategic-mgmt",
    de: {
      title: "Strategic Management",
      subtitle: "Innovation & Change",
      examLabel: "Open Book",
    },
    en: {
      title: "Strategic Management",
      subtitle: "Innovation & Change",
      examLabel: "Open Book",
    },
  },
  {
    slug: "global-strategy",
    de: {
      title: "Global Strategy",
      subtitle: "Internationalisierung",
      examLabel: "Open Book",
    },
    en: {
      title: "Global Strategy",
      subtitle: "Internationalization",
      examLabel: "Open Book",
    },
  },
  {
    slug: "diversification",
    de: {
      title: "Diversification",
      subtitle: "Konzern-Strategien",
      examLabel: "Essay",
    },
    en: {
      title: "Diversification",
      subtitle: "Corporate strategies",
      examLabel: "Essay",
    },
  },
];

type Props = {
  language: Language;
  onTryYourOwn: () => void;
};

export default function DemoPacksSection({ language, onTryYourOwn }: Props) {
  const isEn = language === "en";
  const [activeSlug, setActiveSlug] = useState<string | null>(null);
  const [cache, setCache] = useState<Record<string, StudyPack>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!activeSlug) return;
    if (cache[activeSlug]) return;
    setLoading(true);
    setError(null);
    fetch(`/demo-packs/${activeSlug}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<StudyPack>;
      })
      .then((pack) => {
        setCache((prev) => ({ ...prev, [activeSlug]: pack }));
        track("demo_pack_viewed", {
          slug: activeSlug,
          cards: pack.flashcards.length,
          quiz: pack.simulator.questions.length,
        });
      })
      .catch((e) => {
        setError(e instanceof Error ? e.message : "Load failed");
      })
      .finally(() => setLoading(false));
  }, [activeSlug, cache]);

  const activePack = activeSlug ? cache[activeSlug] : null;

  const heading = isEn
    ? "See what a study pack looks like — no upload needed"
    : "So sieht dein Lernpaket aus — kein Upload nötig";

  const subhead = isEn
    ? "Three real BWL examples from past sessions. Click one, flip through the flashcards, try the quiz — all generated by Lernly."
    : "Drei echte BWL-Beispiele aus vergangenen Sessions. Klick rein, blättere durch die Karten, mach den Quiz — alles von Lernly generiert.";

  return (
    <section
      id="demo"
      className="mx-auto w-full max-w-[1200px] px-6 py-16 md:py-24"
    >
      <div className="mb-10 text-center">
        <p
          className="mb-3 text-[12px] uppercase tracking-[0.2em]"
          style={{ color: "rgba(255,255,255,0.55)" }}
        >
          {isEn ? "Live demo" : "Live-Demo"}
        </p>
        <h2
          className="mx-auto max-w-[720px] text-balance text-[32px] font-bold leading-tight text-white md:text-[44px]"
          style={{ fontFamily: "var(--font-display)" }}
        >
          {heading}
        </h2>
        <p
          className="mx-auto mt-4 max-w-[600px] text-[16px]"
          style={{ color: "rgba(255,255,255,0.6)" }}
        >
          {subhead}
        </p>
      </div>

      <div className="mb-6 flex flex-wrap justify-center gap-3">
        {DEMOS.map((d) => {
          const label = isEn ? d.en : d.de;
          const active = activeSlug === d.slug;
          return (
            <button
              key={d.slug}
              type="button"
              onClick={() => setActiveSlug(d.slug)}
              className={
                "rounded-full border px-5 py-3 text-left transition " +
                (active
                  ? "border-white/40 bg-white/10"
                  : "border-white/10 bg-white/[0.03] hover:border-white/25 hover:bg-white/[0.06]")
              }
            >
              <div className="text-[14px] font-semibold text-white">
                {label.title}
              </div>
              <div
                className="text-[12px]"
                style={{ color: "rgba(255,255,255,0.55)" }}
              >
                {label.subtitle} · {label.examLabel}
              </div>
            </button>
          );
        })}
      </div>

      {!activeSlug && (
        <div
          className="mx-auto mt-10 max-w-[640px] rounded-2xl border border-dashed border-white/15 bg-black/20 px-8 py-12 text-center"
        >
          <p
            className="text-[14px]"
            style={{ color: "rgba(255,255,255,0.55)" }}
          >
            {isEn
              ? "Pick a topic above to load a real pack."
              : "Wähl oben ein Thema, um ein echtes Paket zu laden."}
          </p>
        </div>
      )}

      {loading && (
        <div className="py-10 text-center">
          <span
            className="text-[14px]"
            style={{ color: "rgba(255,255,255,0.6)" }}
          >
            {isEn ? "Loading pack…" : "Pack wird geladen…"}
          </span>
        </div>
      )}

      {error && (
        <div className="py-10 text-center">
          <span className="text-[14px] text-red-300">
            {isEn ? "Failed to load demo." : "Demo konnte nicht geladen werden."}
          </span>
        </div>
      )}

      {activePack && !loading && (
        <>
          <div className="mt-6">
            <PackView pack={activePack} language={language} />
          </div>
          <div className="mt-8 text-center">
            <button
              type="button"
              onClick={() => {
                track("demo_to_upload_clicked", { from_slug: activeSlug });
                onTryYourOwn();
              }}
              className="rounded-full bg-white px-6 py-3 text-[15px] font-semibold text-[#0F1535] hover:bg-white/90"
            >
              {isEn
                ? "Now try with your own PDF →"
                : "Jetzt mit deiner PDF testen →"}
            </button>
          </div>
        </>
      )}
    </section>
  );
}
